FROM node:18-slim
WORKDIR /app
COPY package.json .
# Cài đặt trực tiếp và đưa các file thực thi vào hệ thống container
RUN npm install && npm install -g vite
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev"]