services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: aideom_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: aideom_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Giữ lại node_modules bên trong container không cho máy thật ghi đè
    depends_on:
      - backend